DjangoExamples/urls.py
from django.contrib import admin
from django.urls import path, include

from simple_weather import views as sw
from main_app import views as main
from dia_afa import views as afa
from hello_world import views as hw


urlpatterns = [
    path('', main.index),
    # ONLY EDIT BELOW
    # You can enable admin if you want
    path('admin/', admin.site.urls),

    path('hw/', hw.index, name='index'),
    path('hw/<str:name>', hw.hello, name='hello'),
    path('hw/<str:name>/day', hw.hello_day, name='hello_day'),

    # To add a simple url just remember to provide a name!
    # This name is what shows up on the landing page index.
    path('sw/', sw.index, name='simple_weather'),
    # path('hw/', include('hello_world.urls', 'hello_world')),
    path('afa/', afa.index, name='dia_afa'),
    path('tasks/', include('tasks.urls', 'tasks')),
    path('airline/', include('airline.urls', 'airline')),
    # To include a urls file, remember to provide an app name!
    # This name will show on the landing page index.
    # If you provide an instance namespace, that will show up instead.
    # path('some-app/', include(('some_app.urls', 'some_app'))

]

airline/urls.py
from django.contrib import admin
from django.urls import path
from airline import views

app_name = 'airline'

urlpatterns = [
    path("", views.index, name="index"),
    path("flights/<int:flight_id>", views.flight, name="flight"),
    path("flights/<int:flight_id>/book", views.book, name="book"),
    path("users/", views.user, name="user"),
    path("users/login", views.login_view, name="login"),
    path("users/logout", views.logout_view, name="logout")
]

tasks/urls.py
from django.urls import path
from tasks import views

# Create your urls here.

app_name = 'tasks'

urlpatterns = [
    path("", views.index, name='index'),
    path("add/", views.add, name="add"),
]

airline/models.py
from django.db import models


# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"


class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id} : {self.origin} to {self.destination}"


class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"

airline/views.py
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseBadRequest, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from .models import Flight, Passenger


# Create your views here.
def index(request):
    return render(request, "airline/index.html", {
        "flights": Flight.objects.all()
    })


def user(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("airline:login"))
    return render(request, "airline/user.html")


def flight(request, flight_id):
    try:
        flight = Flight.objects.get(id=flight_id)
    except Flight.DoesNotExist:
        raise Http404("Flight not found.")
    return render(request, "airline/flight.html", {
        "flight": flight,
        "passengers": flight.passengers.all(),
        "non_passengers": Passenger.objects.exclude(flights=flight).all()
    })


def book(request, flight_id):
    if request.method == "POST":
        try:
            passenger = Passenger.objects.get(pk=int(request.POST["passenger"]))
            flight = Flight.objects.get(pk=flight_id)
        except KeyError:
            return HttpResponseBadRequest("Bad Request: no flight chosen")
        except Flight.DoesNotExist:
            return HttpResponseBadRequest("Bad Request: flight does not exist")
        except Passenger.DoesNotExist:
            return HttpResponseBadRequest("Bad Request: passenger does not exist")
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("airline:flight", args=(flight_id,)))


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("airline:index"))
        else:
            return render(request, "airline/login.html", {
                "message": "Invalid credentials."
            })
    else:
        return render(request, "airline/login.html")


def logout_view(request):
    logout(request)
    return render(request, "airline/login.html", {
        "message": "Logged out."
    })

airline/templates/airline/flight.html
{% extends "airline/layout.html" %}

{% block body %}

<h1>Flight {{ flight.id }}</h1>

<ul>
    <li>Origin: {{ flight.origin }}</li>
    <li>Destination: {{ flight.destination }}</li>
    <li>Duration: {{ flight.duration }}</li>
</ul>

<h2>Passengers</h2>

<ul>
    {% for passenger in passengers %}
        <li>{{ passenger }}</li>
    {% empty %}
        <li>No passengers on this flight.</li>
    {% endfor %}
</ul>

<h2>Add Passenger</h2>

<form action="{% url 'airline:book' flight.id %}" method="post">
    {% csrf_token %}
    <select name="passenger">
        {% for passenger in non_passengers %}
            <option value="{{ passenger.id }}">{{ passenger }}</option>
        {% endfor %}
    </select>
    <input type="submit">
</form>

<a href="{% url 'airline:index' %}">Back to Full List</a>

{% endblock %}

airline/templates/airline/index.html
{% extends "airline/layout.html" %}

{% block body %}

    <h1>Flights</h1>
    <ul>
        {% for flight in flights %}
            <li>
                <a href="{% url 'airline:flight' flight.id %}">
                    Flight {{ flight.id }}: {{ flight.origin }} to {{ flight.destination }}
                </a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

airline/templates/airline/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Airline</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

airline/templates/airline/login.html
{% extends "airline/layout.html" %}

{% block body %}

    <h1>Log In</h1>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'airline:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>
{% endblock %}

airline/templates/airline/user.html
{% extends "airline/layout.html" %}

{% block body %}

    <h1>Welcome, {{ request.user.first_name }}</h1>

    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>

    <a href="{% url 'airline:logout' %}">Log Out</a>
{% endblock %}