DjangoExamples/urls.py
from django.contrib import admin
from django.urls import path, include

from simple_weather import views as sw
from main_app import views as main
from dia_afa import views as afa
from hello_world import views as hw


urlpatterns = [
    path('', main.index),
    # ONLY EDIT BELOW
    # You can enable admin if you want
    path('admin/', admin.site.urls),

    path('hw/', hw.index, name='index'),
    path('hw/<str:name>', hw.hello, name='hello'),
    path('hw/<str:name>/day', hw.hello_day, name='hello_day'),

    # To add a simple url just remember to provide a name!
    # This name is what shows up on the landing page index.
    path('sw/', sw.index, name='simple_weather'),
    # path('hw/', include('hello_world.urls', 'hello_world')),
    path('afa/', afa.index, name='dia_afa'),
    path('tasks/', include('tasks.urls', 'tasks')),
    path('airline/', include('airline.urls', 'airline')),
    # To include a urls file, remember to provide an app name!
    # This name will show on the landing page index.
    # If you provide an instance namespace, that will show up instead.
    # path('some-app/', include(('some_app.urls', 'some_app'))

]

tasks/urls.py
from django.urls import path
from tasks import views

# Create your urls here.

app_name = 'tasks'

urlpatterns = [
    path("", views.index, name='index'),
    path("add/", views.add, name="add"),
]

tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse

# Create your views here.


class NewTaskForm(forms.Form):
    # tipos de fields -> Documentação -> Google it
    task = forms.CharField(label="New Task")
    # priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)


tasks = ['alpha', 'bravo', 'charlie']


def index(request):
    return render(request, 'tasks/index.html', {
        'tasks': tasks
    })


def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
    else:
        return render(request, "tasks/add.html", {
            "form": NewTaskForm()
        })


# A lista criada até aqui está guardada numa variável global, ou seja,
# sempre que o website for inicialisado, independentemente do utilizador,
# vai aparecer a mesma lista.
# Para tornar a lista de tarefas pessoal, existe o conceito de sessions.
# mais detalhes em https://docs.djangoproject.com/en/3.1/topics/http/sessions/

# O código a seguir comentado representa o implementado acima mas com este
# novo conceito de sessions.

# def index(request):
#     if "tasks" not in request.session:
#         request.session["tasks"] = []
#     return render(request, "tasks/index.html", {
#         "tasks": request.session["tasks"]
#     })


# def add(request):
#     if request.method == "POST":
#         form = NewTaskForm(request.POST)
#         if form.is_valid():
#             task = form.cleaned_data["task"]
#             request.session["tasks"] += [task]
#             return HttpResponseRedirect(reverse("tasks:index"))
#         else:
#             return render(request, "tasks/add.html", {
#                 "form": form
#             })
#     else:
#         return render(request, "tasks/add.html", {
#             "form": NewTaskForm()
#         })

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    {# <a href="/tasks/index">View All Tasks</a> #}
    <a href="{% url 'tasks:index' %}">View All Tasks</a>
{% endblock %}

{% comment %}
    <form>
        <input type="text" name="task">
        <input type="submit">
    </form>
{% endcomment %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No tasks.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add New Task</a>
{% endblock %}

{% comment %}
    <ul>
        <li>alpha</li>
        <li>bravo</li>
        <li>charlie</li>
    </ul>
{% endcomment %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>